apiVersion: v1
kind: Service
metadata:
  name: aci2019-service-rpi2
spec:
  type: NodePort
  ports:
  - port: 27015
    targetPort: 27015
    protocol: TCP
    nodePort: 30667
  selector:
    app: aci2019-app